/** Auto-synced shapes: section ids must match anchors in module components. */

export type RiggingSlideTocEntry = {readonly id: string; readonly label: string};

export type RiggingSlideModuleConfig = {
  readonly headline: string;
  readonly toc: readonly RiggingSlideTocEntry[];
};

export const RIGGING_SLIDE_MODULE_ORDER = [
  "module-1",
  "module-2",
  "module-3",
  "module-4",
  "module-5",
  "module-6",
  "module-7",
  "module-8",
  "module-9",
  "module-10",
  "module-11",
  "module-12",
  "module-13",
  "module-14",
  "module-15",
  "module-16",
  "module-17",
  "module-18",
  "module-19",
  "module-20",
  "module-21",
  "module-22",
  "module-23",
  "module-24",
  "module-25",
] as const;

export type RiggingSlideModuleSlug = (typeof RIGGING_SLIDE_MODULE_ORDER)[number];

export const RIGGING_SLIDE_MODULE_BY_SLUG: Record<RiggingSlideModuleSlug, RiggingSlideModuleConfig> = {
  "module-1": {
    headline: "Module 1 — Regulations, Standards & Responsibilities | Rigging Education",
    toc: [
      {id: "introduction", label: "Introduction"},
      {id: "why-regulations", label: "Why regulations exist"},
      {id: "regulatory-framework", label: "Regulatory framework"},
      {id: "industry-standards", label: "Industry standards"},
      {id: "competent-qualified", label: "Competent vs qualified"},
      {id: "employer", label: "Employer responsibilities"},
      {id: "supervisor", label: "Supervisor responsibilities"},
      {id: "worker", label: "Worker responsibilities"},
      {id: "refuse-unsafe", label: "Right to refuse unsafe work"},
      {id: "hazard-assessments", label: "Hazard assessments"},
      {id: "site-specific", label: "Site-specific procedures"},
      {id: "documentation", label: "Documentation"},
      {id: "due-diligence", label: "Due diligence"},
    ],
  },
  "module-2": {
    headline: "Module 2 — Rigging Equipment Knowledge | Rigging Education",
    toc: [
      {id: "introduction", label: "Introduction"},
      {id: "system-fundamentals", label: "System fundamentals"},
      {id: "wll", label: "WLL & ratings"},
      {id: "identification", label: "Identification"},
      {id: "shackles", label: "Shackles"},
      {id: "eyebolts", label: "Eyebolts"},
      {id: "hoist-rings", label: "Hoist rings"},
      {id: "hooks", label: "Hooks"},
      {id: "master-links", label: "Master links"},
      {id: "turnbuckles", label: "Turnbuckles"},
      {id: "sling-systems", label: "Sling systems"},
      {id: "wire-rope-slings", label: "Wire rope slings"},
      {id: "chain-slings", label: "Chain slings"},
      {id: "synthetic-web-slings", label: "Web slings"},
      {id: "round-slings", label: "Round slings"},
      {id: "synthetic-rope-hmpe", label: "HMPE / synthetic rope"},
      {id: "below-the-hook", label: "Below-the-hook"},
      {id: "spreader-bars", label: "Spreader bars"},
      {id: "lifting-beams", label: "Lifting beams"},
      {id: "plate-clamps", label: "Plate clamps"},
      {id: "magnets", label: "Magnets"},
      {id: "concrete-buckets", label: "Concrete buckets"},
      {id: "clamshell-buckets", label: "Clamshell buckets"},
      {id: "compatibility", label: "Compatibility"},
      {id: "manufacturer-specs", label: "Manufacturer specs"},
    ],
  },
  "module-3": {
    headline: "Module 3 — Inspection & Removal Criteria | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "purpose-rigging-inspections", label: "Purpose"},
      {id: "inspection-responsibility", label: "Responsibility"},
      {id: "types-inspections", label: "Types of inspection"},
      {id: "wll-verification", label: "WLL verification"},
      {id: "inspection-documentation", label: "Documentation"},
      {id: "general-inspection-principles", label: "General principles"},
      {id: "wire-rope-inspection", label: "Wire rope"},
      {id: "wire-rope-sling-inspection", label: "Wire rope slings"},
      {id: "chain-sling-inspection", label: "Chain slings"},
      {id: "synthetic-sling-inspection", label: "Synthetic slings"},
      {id: "hook-inspection", label: "Hooks"},
      {id: "shackle-inspection", label: "Shackles"},
      {id: "hardware-distortion", label: "Distortion"},
      {id: "unauthorized-modifications", label: "Modifications"},
      {id: "removal-from-service", label: "Removal from service"},
      {id: "storage-handling", label: "Storage & handling"},
      {id: "inspection-culture", label: "Inspection culture"},
    ],
  },
  "module-4": {
    headline: "Module 4 — Crane Awareness for Riggers | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "crane-rigging-relationship", label: "Crane & rigging"},
      {id: "basic-components", label: "Basic components"},
      {id: "hook-block", label: "Hook block"},
      {id: "hoist-rope", label: "Hoist rope"},
      {id: "reeving-awareness", label: "Reeving"},
      {id: "radius-awareness", label: "Radius"},
      {id: "load-chart-awareness", label: "Load charts"},
      {id: "swing-radius", label: "Swing hazards"},
      {id: "load-path", label: "Load path"},
      {id: "blind-lifts", label: "Blind lifts"},
      {id: "powerline-hazards", label: "Powerlines"},
      {id: "limits-of-approach", label: "Limits of approach"},
      {id: "environmental", label: "Environment"},
      {id: "wind-effects", label: "Wind on loads"},
      {id: "dynamic-loading", label: "Dynamic loading"},
      {id: "side-loading", label: "Side loading"},
      {id: "ground-conditions", label: "Ground conditions"},
      {id: "exclusion-zones", label: "Exclusion zones"},
      {id: "communication-coordination", label: "Communication"},
      {id: "lift-planning-awareness", label: "Lift planning"},
      {id: "situational-awareness", label: "Situational awareness"},
    ],
  },
  "module-5": {
    headline: "Module 5 — Basic Rigging Practices | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "system-fundamentals", label: "System fundamentals"},
      {id: "pre-lift", label: "Pre-lift"},
      {id: "wll", label: "WLL"},
      {id: "hitch-configurations", label: "Hitches (overview)"},
      {id: "vertical-hitch", label: "Vertical hitch"},
      {id: "basket-hitch", label: "Basket hitch"},
      {id: "choker-hitch", label: "Choker hitch"},
      {id: "multi-leg", label: "Multi-leg"},
      {id: "sling-angle-effects", label: "Sling angle"},
      {id: "sling-angle-formula", label: "Tension formula"},
      {id: "center-of-gravity", label: "Center of gravity"},
      {id: "cog-awareness", label: "COG awareness"},
      {id: "load-balance", label: "Load balance"},
      {id: "edge-protection", label: "Edge protection"},
      {id: "sling-protection", label: "Sling protection"},
      {id: "taglines", label: "Taglines"},
      {id: "load-path-planning", label: "Load path"},
      {id: "control-zones", label: "Control zones"},
      {id: "landing-loads", label: "Landing"},
      {id: "unhooking", label: "Unhooking"},
      {id: "communication-lifts", label: "Communication"},
      {id: "dynamic-loading-practices", label: "Dynamic loading"},
      {id: "shock-loading", label: "Shock loading"},
      {id: "side-loading-rigging", label: "Side loading"},
      {id: "environmental-rigging", label: "Environment"},
      {id: "situational-awareness", label: "Situational awareness"},
    ],
  },
  "module-6": {
    headline: "Module 6 — Rigging Math & Load Calculations | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "basic-force-concepts", label: "Force concepts"},
      {id: "units-measurement", label: "Units"},
      {id: "weight-estimation", label: "Weight estimation"},
      {id: "material-density", label: "Density"},
      {id: "center-of-gravity", label: "Center of gravity"},
      {id: "cog-formula", label: "COG formula"},
      {id: "load-balance", label: "Load balance"},
      {id: "sling-angle-effects", label: "Sling angle"},
      {id: "sling-angle-formula", label: "T = W/(2 sin θ)"},
      {id: "sling-angle-awareness", label: "Angle awareness"},
      {id: "multi-leg-loading", label: "Multi-leg"},
      {id: "load-sharing", label: "Load sharing"},
      {id: "dynamic-loading-math", label: "Dynamic loading"},
      {id: "shock-loading-math", label: "Shock loading"},
      {id: "static-dynamic-loading", label: "Static vs dynamic"},
      {id: "force-vectors", label: "Force vectors"},
      {id: "force-components", label: "Fx, Fy"},
      {id: "load-moment-concept", label: "Load moment"},
      {id: "load-moment-formula", label: "M = F·d"},
      {id: "radius-awareness-math", label: "Radius"},
      {id: "load-chart-awareness-rigging", label: "Load charts"},
      {id: "rigging-weight", label: "Rigging weight"},
      {id: "safety-factors", label: "Safety factors"},
      {id: "unit-conversions", label: "Conversions"},
      {id: "environmental-calculations", label: "Environment"},
      {id: "engineering-review", label: "Engineering"},
      {id: "calculation-verification", label: "Verification"},
      {id: "situational-awareness-math", label: "Judgment"},
    ],
  },
  "module-7": {
    headline: "Module 7 — Communication & Signaling | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "communication-systems", label: "Systems"},
      {id: "dedicated-signaler", label: "Dedicated signaler"},
      {id: "signaler-responsibilities", label: "Signaler duties"},
      {id: "standard-hand-signals", label: "Hand signals"},
      {id: "hand-signal-visibility", label: "Visibility"},
      {id: "voice-communication", label: "Voice"},
      {id: "radio-communication", label: "Radio"},
      {id: "radio-principles", label: "Radio principles"},
      {id: "recommended-radio-practices", label: "Radio practices"},
      {id: "emergency-stop", label: "Emergency stop"},
      {id: "blind-lifts", label: "Blind lifts"},
      {id: "multi-crane-communication", label: "Multi-crane"},
      {id: "pre-lift-meetings", label: "Pre-lift meetings"},
      {id: "communication-failure", label: "Failure hazards"},
      {id: "environmental-communication", label: "Environment"},
      {id: "situational-awareness-comm", label: "Situational awareness"},
      {id: "human-factors", label: "Human factors"},
      {id: "communication-hierarchy", label: "Hierarchy"},
      {id: "operational-discipline", label: "Discipline"},
      {id: "communication-safety-system", label: "Safety system"},
    ],
  },
  "module-8": {
    headline: "Module 8 — Advanced Sling Geometry & Load Behavior | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "sling-geometry-fundamentals", label: "Geometry fundamentals"},
      {id: "force-distribution", label: "Force distribution"},
      {id: "sling-angle-amplification", label: "Angle amplification"},
      {id: "sling-angle-formula", label: "Angle formula"},
      {id: "horizontal-compression-forces", label: "Compression"},
      {id: "multi-leg-sling-systems", label: "Multi-leg systems"},
      {id: "unequal-sling-loading", label: "Unequal loading"},
      {id: "center-of-gravity-stability", label: "COG & stability"},
      {id: "offset-center-of-gravity", label: "Offset COG"},
      {id: "test-lifts", label: "Test lifts"},
      {id: "load-rotation", label: "Load rotation"},
      {id: "rotational-stability", label: "Rotational stability"},
      {id: "dynamic-load-behavior", label: "Dynamic behavior"},
      {id: "pendulum-effect", label: "Pendulum effect"},
      {id: "load-drift", label: "Load drift"},
      {id: "sling-twist-torque", label: "Twist & torque"},
      {id: "structural-flexing", label: "Structural flexing"},
      {id: "spreader-bars-lifting-beams", label: "Spreaders & beams"},
      {id: "compression-buckling-hazards", label: "Buckling"},
      {id: "environmental-effects-load-behavior", label: "Environment"},
      {id: "engineered-rigging-systems", label: "Engineered systems"},
      {id: "human-factors-judgment", label: "Human factors"},
      {id: "situational-awareness-advanced", label: "Situational awareness"},
    ],
  },
  "module-9": {
    headline: "Module 9 — Advanced Load Control | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "load-control-fundamentals", label: "Fundamentals"},
      {id: "controlled-movement-principles", label: "Movement"},
      {id: "tilting-loads", label: "Tilting"},
      {id: "tilting-hazards", label: "Tilting hazards"},
      {id: "upending-loads", label: "Upending"},
      {id: "upending-considerations", label: "Upending detail"},
      {id: "rotating-loads", label: "Rotation"},
      {id: "rotation-hazards", label: "Rotation hazards"},
      {id: "load-drift-control", label: "Drift"},
      {id: "pendulum-motion", label: "Pendulum"},
      {id: "tagline-use", label: "Taglines"},
      {id: "tagline-safety", label: "Tagline safety"},
      {id: "multi-point-load-control", label: "Multi-point"},
      {id: "precision-placement", label: "Precision"},
      {id: "blind-placement-operations", label: "Blind placement"},
      {id: "dynamic-loading-load-control", label: "Dynamic loading"},
      {id: "snagged-loads", label: "Snagged loads"},
      {id: "wind-effects-load-control", label: "Wind"},
      {id: "boom-deflection-awareness", label: "Boom deflection"},
      {id: "load-stabilization-techniques", label: "Stabilization"},
      {id: "human-factors-load-control", label: "Human factors"},
      {id: "situational-awareness-load-control", label: "Situational awareness"},
    ],
  },
  "module-10": {
    headline: "Module 10 — Chainfalls, Lever Hoists & Tensioning Devices | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "chainfalls", label: "Chainfalls"},
      {id: "chainfall-components", label: "Chainfall parts"},
      {id: "chainfall-operation-principles", label: "Operation"},
      {id: "chainfall-hazards", label: "Chainfall hazards"},
      {id: "chainfall-side-loading", label: "Side loading"},
      {id: "lever-hoists", label: "Lever hoists"},
      {id: "lever-hoist-components", label: "Lever parts"},
      {id: "lever-hoist-hazards", label: "Lever hazards"},
      {id: "tensioning-operations", label: "Tensioning"},
      {id: "stored-energy-hazards", label: "Stored energy"},
      {id: "snap-back-zones", label: "Snap-back"},
      {id: "anchoring-considerations", label: "Anchoring"},
      {id: "structural-loading-awareness", label: "Structure loads"},
      {id: "shock-loading-tensioning", label: "Shock loading"},
      {id: "hook-inspection-loading", label: "Hooks"},
      {id: "chain-inspection", label: "Chain inspection"},
      {id: "brake-systems", label: "Brakes"},
      {id: "environmental-conditions-hoists", label: "Environment"},
      {id: "communication-tensioning", label: "Communication"},
      {id: "temporary-stabilization-systems", label: "Temporary systems"},
      {id: "human-factors-tensioning", label: "Human factors"},
      {id: "situational-awareness-tensioning", label: "Situational awareness"},
    ],
  },
  "module-11": {
    headline: "Module 11 — Multiple Crane & Tandem Lifts | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "why-multiple-cranes", label: "Why multiple cranes"},
      {id: "tandem-complexity", label: "Complexity"},
      {id: "load-sharing-fundamentals", label: "Load sharing"},
      {id: "unequal-load-sharing", label: "Unequal sharing"},
      {id: "dynamic-load-transfer-tandem", label: "Dynamic transfer"},
      {id: "cog-tandem-lifts", label: "Center of gravity"},
      {id: "crane-capacity-awareness-tandem", label: "Capacity"},
      {id: "radius-effects-tandem-lifts", label: "Radius effects"},
      {id: "boom-deflection-tandem-lifts", label: "Boom deflection"},
      {id: "hoisting-coordination-tandem", label: "Hoisting coordination"},
      {id: "communication-systems-tandem", label: "Communication"},
      {id: "communication-requirements-tandem", label: "Comm requirements"},
      {id: "lift-director-role", label: "Lift director"},
      {id: "pre-lift-planning-tandem", label: "Pre-lift planning"},
      {id: "engineered-lift-plans-tandem", label: "Engineered plans"},
      {id: "environmental-tandem-lifts", label: "Environment"},
      {id: "swing-control-load-rotation-tandem", label: "Swing & rotation"},
      {id: "exclusion-zones-tandem", label: "Exclusion zones"},
      {id: "human-factors-tandem-lifts", label: "Human factors"},
      {id: "situational-awareness-multiple-crane", label: "Situational awareness"},
    ],
  },
  "module-12": {
    headline: "Module 12 — Specialty Lifting Devices & Attachments | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "bth-lifting-devices", label: "BTH devices"},
      {id: "engineered-devices-specialty", label: "Engineered devices"},
      {id: "spreader-bars-bth", label: "Spreader bars"},
      {id: "spreader-bar-force-behavior", label: "Spreader forces"},
      {id: "spreader-bar-hazards-bth", label: "Spreader hazards"},
      {id: "lifting-beams-bth", label: "Lifting beams"},
      {id: "lifting-beam-hazards-bth", label: "Beam hazards"},
      {id: "plate-clamps", label: "Plate clamps"},
      {id: "plate-clamp-hazards", label: "Clamp hazards"},
      {id: "plate-clamp-operational", label: "Clamp operation"},
      {id: "lifting-magnets", label: "Magnets"},
      {id: "magnet-lifting-hazards", label: "Magnet hazards"},
      {id: "magnet-surface-conditions", label: "Magnet surfaces"},
      {id: "vacuum-lifting-devices", label: "Vacuum lifts"},
      {id: "vacuum-lifting-hazards", label: "Vacuum hazards"},
      {id: "concrete-buckets", label: "Concrete buckets"},
      {id: "concrete-bucket-hazards", label: "Bucket hazards"},
      {id: "clamshell-buckets", label: "Clamshell"},
      {id: "clamshell-hazards", label: "Clamshell hazards"},
      {id: "personnel-lifting-devices", label: "Personnel lifts"},
      {id: "custom-engineered-attachments", label: "Custom BTH"},
      {id: "load-attachment-points-specialty", label: "Attachment points"},
      {id: "inspection-requirements-specialty", label: "Inspection"},
      {id: "capacity-verification-bth", label: "Capacity"},
      {id: "environmental-specialty-lifts", label: "Environment"},
      {id: "communication-coordination-specialty", label: "Communication"},
      {id: "human-factors-specialty-lifts", label: "Human factors"},
      {id: "situational-awareness-specialty-lifts", label: "Situational awareness"},
    ],
  },
  "module-13": {
    headline: "Module 13 — Crane Physics for Riggers | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "gravity", label: "Gravity"},
      {id: "force-transfer", label: "Force transfer"},
      {id: "load-paths", label: "Load paths"},
      {id: "static-loads", label: "Static loads"},
      {id: "dynamic-loads", label: "Dynamic loads"},
      {id: "dynamic-loading-sources", label: "Dynamic sources"},
      {id: "shock-loading", label: "Shock loading"},
      {id: "force-vectors", label: "Force vectors"},
      {id: "horizontal-vertical-components", label: "Force components"},
      {id: "sling-angle-physics", label: "Sling angle"},
      {id: "sling-angle-formula", label: "Sling tension formula"},
      {id: "compression-forces", label: "Compression"},
      {id: "tension-forces", label: "Tension"},
      {id: "shear-forces", label: "Shear"},
      {id: "bending-forces", label: "Bending"},
      {id: "torsion-twisting", label: "Torsion"},
      {id: "center-of-gravity-crane-physics", label: "Center of gravity"},
      {id: "center-of-gravity-formula", label: "COG formula"},
      {id: "equilibrium", label: "Equilibrium"},
      {id: "pendulum-effect", label: "Pendulum effect"},
      {id: "load-moment", label: "Load moment"},
      {id: "load-moment-formula", label: "Moment formula"},
      {id: "boom-deflection", label: "Boom deflection"},
      {id: "ground-bearing-pressure", label: "Ground pressure"},
      {id: "environmental-physics", label: "Environment"},
      {id: "human-factors-judgment-physics", label: "Human factors"},
      {id: "situational-awareness-forces", label: "Situational awareness"},
    ],
  },
  "module-14": {
    headline: "Module 14 — Environmental & Site Hazards | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "environmental-awareness-lifting", label: "Environmental awareness"},
      {id: "wind-hazards", label: "Wind"},
      {id: "windsail-effect", label: "Windsail effect"},
      {id: "wind-dynamic-loading", label: "Wind & dynamic load"},
      {id: "wind-monitoring", label: "Wind monitoring"},
      {id: "wind-operational-limits", label: "Wind limits"},
      {id: "rain-moisture-hazards", label: "Rain & moisture"},
      {id: "ice-snow-hazards", label: "Ice & snow"},
      {id: "temperature-effects", label: "Temperature"},
      {id: "lightning-hazards", label: "Lightning"},
      {id: "reduced-visibility", label: "Visibility"},
      {id: "ground-conditions-site", label: "Ground conditions"},
      {id: "soil-bearing-capacity-site", label: "Soil bearing"},
      {id: "underground-hazards", label: "Underground"},
      {id: "site-congestion", label: "Site congestion"},
      {id: "overhead-hazards", label: "Overhead"},
      {id: "powerline-hazards", label: "Powerlines"},
      {id: "traffic-mobile-equipment", label: "Traffic & equipment"},
      {id: "public-exposure-hazards", label: "Public exposure"},
      {id: "environmental-decision-making", label: "Decision-making"},
      {id: "human-factors-environmental", label: "Human factors"},
      {id: "situational-awareness-environmental", label: "Situational awareness"},
    ],
  },
  "module-15": {
    headline: "Module 15 — Lift Planning & Critical Lifts | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "purpose-lift-planning", label: "Purpose of planning"},
      {id: "pre-lift-planning-fundamentals", label: "Pre-lift fundamentals"},
      {id: "load-weight-verification", label: "Load weight"},
      {id: "center-of-gravity-evaluation-planning", label: "Center of gravity"},
      {id: "crane-configuration-planning", label: "Crane configuration"},
      {id: "radius-awareness-planning", label: "Radius"},
      {id: "load-path-planning", label: "Load path"},
      {id: "landing-area-planning", label: "Landing area"},
      {id: "ground-condition-evaluation-planning", label: "Ground conditions"},
      {id: "environmental-planning-lifts", label: "Environment"},
      {id: "rigging-selection-planning", label: "Rigging selection"},
      {id: "communication-planning-lifts", label: "Communication"},
      {id: "exclusion-zones-personnel-control", label: "Exclusion zones"},
      {id: "pre-lift-meetings", label: "Pre-lift meetings"},
      {id: "critical-lifts-overview", label: "Critical lifts"},
      {id: "examples-critical-lifts", label: "Critical lift examples"},
      {id: "engineered-lift-plans", label: "Engineered plans"},
      {id: "lift-director-role", label: "Lift director"},
      {id: "contingency-planning-lifts", label: "Contingency"},
      {id: "dynamic-loading-considerations-planning", label: "Dynamic loading"},
      {id: "human-factors-lift-planning", label: "Human factors"},
      {id: "documentation-operational-records", label: "Documentation"},
      {id: "situational-awareness-lift-operations", label: "Situational awareness"},
    ],
  },
  "module-16": {
    headline: "Module 16 — Practical Rigging Applications & Field Operations | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "field-level-hazard-awareness", label: "Field hazards"},
      {id: "lift-area-preparation", label: "Lift area prep"},
      {id: "rigging-preparation-field", label: "Rigging prep"},
      {id: "pre-lift-inspection-field", label: "Pre-lift inspection"},
      {id: "test-lifts", label: "Test lifts"},
      {id: "controlled-hoisting", label: "Controlled hoisting"},
      {id: "swing-control-field", label: "Swing control"},
      {id: "load-rotation-control", label: "Load rotation"},
      {id: "tagline-operations", label: "Taglines"},
      {id: "blind-lift-operations", label: "Blind lifts"},
      {id: "structural-steel-operations", label: "Structural steel"},
      {id: "concrete-operations-field", label: "Concrete"},
      {id: "mechanical-equipment-lifting", label: "Mechanical equipment"},
      {id: "modular-prefabricated-components", label: "Modular / prefab"},
      {id: "confined-restricted-work-areas", label: "Confined areas"},
      {id: "night-operations-reduced-visibility", label: "Night / visibility"},
      {id: "personnel-positioning-field", label: "Personnel positioning"},
      {id: "exclusion-zones-field", label: "Exclusion zones"},
      {id: "communication-field-operations", label: "Communication"},
      {id: "environmental-monitoring-operations", label: "Environment"},
      {id: "human-factors-field-operations", label: "Human factors"},
      {id: "situational-awareness-practical-rigging", label: "Situational awareness"},
    ],
  },
  "module-17": {
    headline: "Module 17 — Rigging Safety Culture, Human Factors & Operational Decision-Making | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "safety-culture", label: "Safety culture"},
      {id: "shared-responsibility-lifting", label: "Shared responsibility"},
      {id: "human-factors-lifting-operations", label: "Human factors"},
      {id: "fatigue-lifting-safety", label: "Fatigue"},
      {id: "complacency-lifting", label: "Complacency"},
      {id: "time-pressure-production", label: "Time / production pressure"},
      {id: "assumptions-miscommunication", label: "Assumptions & comms"},
      {id: "situational-awareness-lifting-culture", label: "Situational awareness"},
      {id: "loss-situational-awareness", label: "Loss of awareness"},
      {id: "stop-work-authority", label: "Stop work authority"},
      {id: "communication-culture", label: "Communication culture"},
      {id: "operational-discipline", label: "Operational discipline"},
      {id: "learning-incidents-near-misses", label: "Incidents & near misses"},
      {id: "hazard-recognition-operations", label: "Hazard recognition"},
      {id: "decision-making-during-lifts", label: "Decisions during lifts"},
      {id: "leadership-supervisory-influence", label: "Leadership"},
      {id: "team-coordination-lifting", label: "Team coordination"},
      {id: "environmental-stress-worker-performance", label: "Environmental stress"},
      {id: "continuous-improvement-rigging", label: "Continuous improvement"},
      {id: "professionalism-rigging-operations", label: "Professionalism"},
      {id: "situational-awareness-culture-integration", label: "Integration"},
    ],
  },
  "module-18": {
    headline: "Module 18 — Rigging Reference Tables, Field Guidelines & Operational Awareness | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "sling-angle-awareness-table", label: "Sling angle"},
      {id: "common-sling-angle-multipliers", label: "Angle multipliers"},
      {id: "sling-angle-formula-reference", label: "Angle formula"},
      {id: "basic-weight-estimation-awareness", label: "Weight estimation"},
      {id: "approximate-material-weights", label: "Material weights"},
      {id: "basic-wire-rope-inspection-awareness", label: "Wire rope inspection"},
      {id: "running-rope-removal-criteria", label: "Running rope 3–6"},
      {id: "rotation-resistant-rope-removal-criteria", label: "Rotation-resistant"},
      {id: "wire-rope-sling-awareness", label: "Wire rope slings"},
      {id: "synthetic-sling-awareness", label: "Synthetic slings"},
      {id: "chain-sling-awareness", label: "Chain slings"},
      {id: "hook-inspection-awareness", label: "Hooks"},
      {id: "shackle-awareness", label: "Shackles"},
      {id: "common-dynamic-loading-sources", label: "Dynamic loading"},
      {id: "common-load-control-hazards", label: "Load control"},
      {id: "common-environmental-hazards", label: "Environment"},
      {id: "powerline-awareness", label: "Powerlines"},
      {id: "exclusion-zone-awareness-reference", label: "Exclusion zones"},
      {id: "tagline-awareness-reference", label: "Taglines"},
      {id: "blind-lift-awareness-reference", label: "Blind lifts"},
      {id: "multi-crane-lift-awareness", label: "Multi-crane"},
      {id: "ground-condition-awareness", label: "Ground conditions"},
      {id: "basic-lift-planning-awareness", label: "Lift planning"},
      {id: "human-factors-awareness-reference", label: "Human factors"},
      {id: "situational-awareness-reminder", label: "Situational awareness"},
    ],
  },
  "module-19": {
    headline: "Module 19 — Glossary of Crane & Rigging Terms | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "glossary-terms", label: "All terms"},
      {id: "abrasion", label: "Abrasion"},
      {id: "anchor-shackle", label: "Anchor shackle"},
      {id: "birdcaging", label: "Birdcaging"},
      {id: "blind-lift", label: "Blind lift"},
      {id: "boom", label: "Boom"},
      {id: "boom-deflection", label: "Boom deflection"},
      {id: "center-of-gravity", label: "Center of gravity"},
      {id: "chainfall", label: "Chainfall"},
      {id: "choker-hitch", label: "Choker hitch"},
      {id: "competent-person", label: "Competent person"},
      {id: "critical-lift", label: "Critical lift"},
      {id: "dynamic-load", label: "Dynamic load"},
      {id: "equalizing-beam", label: "Equalizing beam"},
      {id: "exclusion-zone", label: "Exclusion zone"},
      {id: "force-vector", label: "Force vector"},
      {id: "ground-bearing-pressure", label: "Ground bearing pressure"},
      {id: "hitch", label: "Hitch"},
      {id: "hoist-rope", label: "Hoist rope"},
      {id: "hook-block", label: "Hook block"},
      {id: "horizontal-force", label: "Horizontal force"},
      {id: "kink", label: "Kink"},
      {id: "lay-length", label: "Lay length"},
      {id: "lift-director", label: "Lift director"},
      {id: "lift-plan", label: "Lift plan"},
      {id: "lifting-beam", label: "Lifting beam"},
      {id: "load-moment", label: "Load moment"},
      {id: "load-moment-formula", label: "Load moment M=F×d"},
      {id: "load-path", label: "Load path"},
      {id: "mechanical-advantage", label: "Mechanical advantage"},
      {id: "multi-leg-sling", label: "Multi-leg sling"},
      {id: "non-rotational-rope", label: "Non-rotational rope"},
      {id: "pendant-line", label: "Pendant line"},
      {id: "pendulum-effect", label: "Pendulum effect"},
      {id: "pick-point", label: "Pick point"},
      {id: "radius", label: "Radius"},
      {id: "reeving", label: "Reeving"},
      {id: "rigging-hardware", label: "Rigging hardware"},
      {id: "rotation-resistant-rope", label: "Rotation-resistant rope"},
      {id: "running-rope", label: "Running rope"},
      {id: "shock-loading", label: "Shock loading"},
      {id: "side-loading", label: "Side loading"},
      {id: "sling-angle", label: "Sling angle"},
      {id: "sling-angle-formula", label: "Sling angle formula"},
      {id: "snap-back-zone", label: "Snap-back zone"},
      {id: "spreader-bar", label: "Spreader bar"},
      {id: "static-load", label: "Static load"},
      {id: "stored-energy", label: "Stored energy"},
      {id: "tagline", label: "Tagline"},
      {id: "tandem-lift", label: "Tandem lift"},
      {id: "test-lift", label: "Test lift"},
      {id: "throat-opening", label: "Throat opening"},
      {id: "torsion", label: "Torsion"},
      {id: "vertical-hitch", label: "Vertical hitch"},
      {id: "working-load-limit-wll", label: "WLL / SWL"},
    ],
  },
  "module-20": {
    headline: "Module 20 — Final Integration: Applied Rigging Knowledge & Operational Readiness | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "integrated-lift-awareness", label: "Integrated awareness"},
      {id: "rigging-system-force-network", label: "Force network"},
      {id: "situational-awareness-continuous-process", label: "Situational awareness"},
      {id: "hazard-recognition-integration", label: "Hazard integration"},
      {id: "communication-coordination-lifting", label: "Communication"},
      {id: "operational-discipline-readiness", label: "Discipline"},
      {id: "human-factors-decision-making", label: "Human factors"},
      {id: "environmental-integration-operations", label: "Environment"},
      {id: "dynamic-load-awareness-integration", label: "Dynamic loads"},
      {id: "critical-thinking-rigging-operations", label: "Critical thinking"},
      {id: "professionalism-rigging-career", label: "Professionalism"},
      {id: "continuous-learning-rigging", label: "Continuous learning"},
      {id: "team-based-operations", label: "Team operations"},
      {id: "operational-readiness", label: "Readiness"},
      {id: "emergency-awareness-lifting", label: "Emergency awareness"},
      {id: "final-situational-awareness-principles", label: "SA principles"},
      {id: "final-course-integration-summary", label: "Course summary"},
    ],
  },
  "module-21": {
    headline: "Module 21 — Knots, Hitches & Rope Applications | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "rope-types", label: "Rope types"},
      {id: "natural-fibre-rope", label: "Natural fibre"},
      {id: "synthetic-rope", label: "Synthetic"},
      {id: "rope-construction-types", label: "Construction"},
      {id: "rope-stretch-characteristics", label: "Stretch"},
      {id: "rope-inspection", label: "Inspection"},
      {id: "rope-storage", label: "Storage"},
      {id: "knot-efficiency", label: "Knot efficiency"},
      {id: "common-rope-hazards", label: "Hazards"},
      {id: "bowline-knot", label: "Bowline"},
      {id: "running-bowline", label: "Running bowline"},
      {id: "figure-eight-knot", label: "Figure eight"},
      {id: "figure-eight-follow-through", label: "Fig. eight follow-through"},
      {id: "clove-hitch", label: "Clove hitch"},
      {id: "timber-hitch", label: "Timber hitch"},
      {id: "rolling-hitch", label: "Rolling hitch"},
      {id: "half-hitch", label: "Half hitch"},
      {id: "sheet-bend", label: "Sheet bend"},
      {id: "tagline-rope-applications", label: "Taglines"},
      {id: "rope-tensioning-awareness", label: "Tensioning"},
      {id: "snap-back-zones", label: "Snap-back"},
      {id: "rope-abrasion-protection", label: "Abrasion"},
      {id: "heat-chemical-exposure", label: "Heat & chemicals"},
      {id: "human-factors-rope-operations", label: "Human factors"},
      {id: "situational-awareness-rope-operations", label: "Situational awareness"},
    ],
  },
  "module-22": {
    headline: "Module 22 — Block & Tackle, Reeving & Mechanical Advantage Systems | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "mechanical-advantage", label: "Mechanical advantage"},
      {id: "ideal-mechanical-advantage-formula", label: "IMA formula"},
      {id: "actual-mechanical-advantage", label: "Actual MA"},
      {id: "sheaves", label: "Sheaves"},
      {id: "sheave-diameter-awareness", label: "Sheave diameter"},
      {id: "blocks", label: "Blocks"},
      {id: "snatch-blocks", label: "Snatch blocks"},
      {id: "snatch-block-hazards", label: "Snatch hazards"},
      {id: "reeving", label: "Reeving"},
      {id: "improper-reeving-hazards", label: "Improper reeving"},
      {id: "single-part-line", label: "Single-part"},
      {id: "multi-part-line", label: "Multi-part"},
      {id: "reeving-efficiency", label: "Efficiency"},
      {id: "directional-force-changes", label: "Force direction"},
      {id: "fleet-angle", label: "Fleet angle"},
      {id: "rope-tension-systems", label: "Tension systems"},
      {id: "stored-energy-hazards-mechanical-advantage", label: "Stored energy"},
      {id: "snap-back-zones-block-tackle", label: "Snap-back"},
      {id: "gin-poles-derrick-concepts", label: "Gin pole / derrick"},
      {id: "highline-redirect-systems", label: "Highline"},
      {id: "wire-rope-reeving-awareness", label: "Wire rope reeving"},
      {id: "side-loading-hazards-blocks", label: "Side loading"},
      {id: "inspection-requirements-mechanical-advantage", label: "Inspection"},
      {id: "human-factors-reeving-operations", label: "Human factors"},
      {id: "situational-awareness-reeving-operations", label: "Situational awareness"},
    ],
  },
  "module-23": {
    headline: "Module 23 — Heavy Lift Engineering & Advanced Rigging Systems | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "engineered-lift-philosophy", label: "Lift philosophy"},
      {id: "engineered-lift-plans", label: "Lift plans"},
      {id: "ground-bearing-engineering", label: "Ground bearing"},
      {id: "lift-mats-support-systems", label: "Mats & support"},
      {id: "strand-jack-systems", label: "Strand jacks"},
      {id: "strand-jack-advantages", label: "Strand jack pros"},
      {id: "hydraulic-gantry-systems", label: "Hydraulic gantries"},
      {id: "gantry-hazards", label: "Gantry hazards"},
      {id: "skidding-systems", label: "Skidding"},
      {id: "skidding-hazards", label: "Skidding hazards"},
      {id: "jack-slide-operations", label: "Jack & slide"},
      {id: "spmts-self-propelled-modular-transporters", label: "SPMTs"},
      {id: "spmt-operational-hazards", label: "SPMT hazards"},
      {id: "equalizing-systems", label: "Equalizing"},
      {id: "unequal-load-sharing", label: "Load sharing"},
      {id: "engineered-lift-lugs", label: "Lift lugs"},
      {id: "lift-frame-systems", label: "Lift frames"},
      {id: "structural-flexing-deflection", label: "Deflection"},
      {id: "dynamic-load-modeling", label: "Dynamic modeling"},
      {id: "wind-engineering-considerations", label: "Wind"},
      {id: "multi-crane-engineering", label: "Multi-crane"},
      {id: "load-out-marine-operations", label: "Marine / load-out"},
      {id: "monitoring-instrumentation", label: "Monitoring"},
      {id: "redundancy-engineered-systems", label: "Redundancy"},
      {id: "human-factors-heavy-lift-operations", label: "Human factors"},
      {id: "situational-awareness-heavy-lift-operations", label: "Situational awareness"},
    ],
  },
  "module-24": {
    headline: "Module 24 — Tower Crane Rigging Operations | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "tower-crane-characteristics", label: "Characteristics"},
      {id: "common-tower-crane-types", label: "Crane types"},
      {id: "hammerhead-tower-cranes", label: "Hammerhead"},
      {id: "luffing-jib-tower-cranes", label: "Luffing jib"},
      {id: "self-erecting-tower-cranes", label: "Self-erecting"},
      {id: "tower-crane-radius-awareness", label: "Radius"},
      {id: "trolley-dynamics-tower-crane", label: "Trolley"},
      {id: "tower-crane-hook-approach", label: "Hook approach"},
      {id: "blind-lift-operations-tower-cranes", label: "Blind lifts"},
      {id: "radio-communication-discipline-tower-cranes", label: "Radio"},
      {id: "concrete-bucket-operations", label: "Concrete buckets"},
      {id: "formwork-fly-form-operations", label: "Formwork / fly form"},
      {id: "rebar-cage-long-load-operations", label: "Long loads"},
      {id: "wind-exposure-at-elevation", label: "Wind at height"},
      {id: "windsail-effect-tower-crane", label: "Windsail"},
      {id: "urban-site-hazards-tower-cranes", label: "Urban hazards"},
      {id: "public-protection-tower-cranes", label: "Public protection"},
      {id: "multiple-tower-crane-operations", label: "Multi-crane"},
      {id: "anti-collision-systems-tower-cranes", label: "Anti-collision"},
      {id: "climbing-operations-awareness", label: "Climbing"},
      {id: "tower-crane-erection-awareness", label: "Erection / dismantle"},
      {id: "out-of-service-wind-procedures", label: "Out-of-service wind"},
      {id: "human-factors-tower-crane-operations", label: "Human factors"},
      {id: "situational-awareness-tower-crane-rigging", label: "Situational awareness"},
    ],
  },
  "module-25": {
    headline: "Module 25 — Rigging Incident Case Studies & Failure Analysis | Rigging Education",
    toc: [
      {id: "regulatory-references", label: "Standards references"},
      {id: "introduction", label: "Introduction"},
      {id: "incident-analysis-principles", label: "Analysis principles"},
      {id: "immediate-cause-vs-root-cause", label: "Immediate vs root cause"},
      {id: "immediate-cause-definition", label: "Immediate cause"},
      {id: "root-cause-definition", label: "Root cause"},
      {id: "case-study-sling-angle-overload", label: "Case: sling angle"},
      {id: "incident-overview-sling-angle-overload", label: "Sling angle — overview"},
      {id: "immediate-cause-sling-angle-overload", label: "Sling angle — cause"},
      {id: "contributing-factors-sling-angle-overload", label: "Sling angle — factors"},
      {id: "operational-lessons-sling-angle-overload", label: "Sling angle — lessons"},
      {id: "sling-angle-formula-reminder-case-study", label: "Sling formula"},
      {id: "case-study-shock-loading-failure", label: "Case: shock load"},
      {id: "incident-overview-shock-loading", label: "Shock — overview"},
      {id: "immediate-cause-shock-loading", label: "Shock — cause"},
      {id: "contributing-factors-shock-loading", label: "Shock — factors"},
      {id: "operational-lessons-shock-loading", label: "Shock — lessons"},
      {id: "case-study-side-loaded-shackle-failure", label: "Case: shackle"},
      {id: "incident-overview-side-loaded-shackle", label: "Shackle — overview"},
      {id: "immediate-cause-side-loaded-shackle", label: "Shackle — cause"},
      {id: "contributing-factors-side-loaded-shackle", label: "Shackle — factors"},
      {id: "operational-lessons-side-loaded-shackle", label: "Shackle — lessons"},
      {id: "case-study-powerline-contact", label: "Case: powerline"},
      {id: "incident-overview-powerline-contact", label: "Powerline — overview"},
      {id: "immediate-cause-powerline-contact", label: "Powerline — cause"},
      {id: "contributing-factors-powerline-contact", label: "Powerline — factors"},
      {id: "operational-lessons-powerline-contact", label: "Powerline — lessons"},
      {id: "case-study-wind-induced-load-instability", label: "Case: wind"},
      {id: "incident-overview-wind-induced-instability", label: "Wind — overview"},
      {id: "immediate-cause-wind-induced-instability", label: "Wind — cause"},
      {id: "contributing-factors-wind-induced-instability", label: "Wind — factors"},
      {id: "operational-lessons-wind-induced-instability", label: "Wind — lessons"},
      {id: "case-study-ground-failure-crane-instability", label: "Case: ground"},
      {id: "incident-overview-ground-failure-crane", label: "Ground — overview"},
      {id: "immediate-cause-ground-failure-crane", label: "Ground — cause"},
      {id: "contributing-factors-ground-failure-crane", label: "Ground — factors"},
      {id: "operational-lessons-ground-failure-crane", label: "Ground — lessons"},
      {id: "case-study-multiple-crane-lift-failure", label: "Case: multi-crane"},
      {id: "incident-overview-multiple-crane-lift", label: "Multi-crane — overview"},
      {id: "immediate-cause-multiple-crane-lift", label: "Multi-crane — cause"},
      {id: "contributing-factors-multiple-crane-lift", label: "Multi-crane — factors"},
      {id: "operational-lessons-multiple-crane-lift", label: "Multi-crane — lessons"},
      {id: "human-factors-in-rigging-incidents", label: "Human factors"},
      {id: "incident-prevention-through-planning", label: "Prevention"},
      {id: "learning-from-near-misses-rigging", label: "Near misses"},
      {id: "situational-awareness-incident-prevention", label: "Situational awareness"},
    ],
  },
};

export function riggingSlideSlugForModuleNumber(n: number): RiggingSlideModuleSlug | null {
  if (n < 1 || n > 25) return null;
  return `module-${n}` as RiggingSlideModuleSlug;
}

export function parseRiggingSlideModuleSlug(slug: string): number | null {
  const m = /^module-(\d+)$/.exec(slug);
  if (!m) return null;
  const n = parseInt(m[1], 10);
  if (n < 1 || n > 25) return null;
  return n;
}

export function isRiggingSlideModuleSlug(slug: string): slug is RiggingSlideModuleSlug {
  return slug in RIGGING_SLIDE_MODULE_BY_SLUG;
}
